baseURL: "https://13mai13.github.io/"
title: "Mai's Site"
footnoteReturnLinkContents: "↩"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Hugo is Absurdly Fast!"
  AuthorName: "Jon Doe"
  GitHubUser: "spf13"
  ListOfFoo:
    - "foo1"
    - "foo2"
  SidebarRecentLimit: 5

themesDir: "themes"
theme: "paper"

twitter: "@MaialenBerrondo"              
github: "13Mai13"                        
linkedin: "maialen-berrondo-43197b94"